name: quran
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  path: ^1.9.0
  path_provider: ^2.1.2
  preload_page_view: ^0.2.0
  scrollable_positioned_list: ^0.3.8
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/quran/
    - assets/images/quran/tilawah_1/
    - assets/databases/
    - assets/fonts/

  fonts:
    - family: SuraNames
      fonts:
        - asset: assets/fonts/sura_names.ttf
    - family: UthmanicHafs_V22
      fonts:
        - asset: assets/fonts/UthmanicHafs_V22.ttf
    - family: LPMQ
      fonts:
        - asset: assets/fonts/LPMQ.ttf
    - family: Bismillah
      fonts:
        - asset: assets/fonts/bismillah.ttf
